// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "calcHaarPattern_x_y.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic calcHaarPattern_x_y::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic calcHaarPattern_x_y::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<10> calcHaarPattern_x_y::ap_ST_fsm_state1 = "1";
const sc_lv<10> calcHaarPattern_x_y::ap_ST_fsm_state2 = "10";
const sc_lv<10> calcHaarPattern_x_y::ap_ST_fsm_state3 = "100";
const sc_lv<10> calcHaarPattern_x_y::ap_ST_fsm_state4 = "1000";
const sc_lv<10> calcHaarPattern_x_y::ap_ST_fsm_state5 = "10000";
const sc_lv<10> calcHaarPattern_x_y::ap_ST_fsm_state6 = "100000";
const sc_lv<10> calcHaarPattern_x_y::ap_ST_fsm_state7 = "1000000";
const sc_lv<10> calcHaarPattern_x_y::ap_ST_fsm_state8 = "10000000";
const sc_lv<10> calcHaarPattern_x_y::ap_ST_fsm_state9 = "100000000";
const sc_lv<10> calcHaarPattern_x_y::ap_ST_fsm_state10 = "1000000000";
const sc_lv<32> calcHaarPattern_x_y::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> calcHaarPattern_x_y::ap_const_lv32_1 = "1";
const sc_lv<32> calcHaarPattern_x_y::ap_const_lv32_2 = "10";
const sc_lv<32> calcHaarPattern_x_y::ap_const_lv32_3 = "11";
const sc_lv<32> calcHaarPattern_x_y::ap_const_lv32_4 = "100";
const sc_lv<32> calcHaarPattern_x_y::ap_const_lv32_5 = "101";
const sc_lv<32> calcHaarPattern_x_y::ap_const_lv32_6 = "110";
const sc_lv<32> calcHaarPattern_x_y::ap_const_lv32_7 = "111";
const sc_lv<32> calcHaarPattern_x_y::ap_const_lv32_8 = "1000";
const sc_lv<32> calcHaarPattern_x_y::ap_const_lv32_9 = "1001";
const sc_lv<2> calcHaarPattern_x_y::ap_const_lv2_0 = "00";
const sc_lv<7> calcHaarPattern_x_y::ap_const_lv7_1 = "1";
const sc_lv<2> calcHaarPattern_x_y::ap_const_lv2_3 = "11";
const sc_lv<2> calcHaarPattern_x_y::ap_const_lv2_1 = "1";
const sc_lv<32> calcHaarPattern_x_y::ap_const_lv32_A = "1010";
const sc_lv<32> calcHaarPattern_x_y::ap_const_lv32_1F = "11111";
const sc_lv<10> calcHaarPattern_x_y::ap_const_lv10_0 = "0000000000";
const sc_lv<22> calcHaarPattern_x_y::ap_const_lv22_1 = "1";
const sc_lv<32> calcHaarPattern_x_y::ap_const_lv32_19 = "11001";
const sc_lv<3> calcHaarPattern_x_y::ap_const_lv3_0 = "000";
const sc_lv<27> calcHaarPattern_x_y::ap_const_lv27_7FFFFFF = "111111111111111111111111111";
const sc_lv<32> calcHaarPattern_x_y::ap_const_lv32_AF = "10101111";
const sc_lv<8> calcHaarPattern_x_y::ap_const_lv8_AF = "10101111";
const sc_lv<176> calcHaarPattern_x_y::ap_const_lv176_lc_1 = "11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111";
const sc_lv<16> calcHaarPattern_x_y::ap_const_lv16_321 = "1100100001";
const sc_lv<1> calcHaarPattern_x_y::ap_const_lv1_1 = "1";
const bool calcHaarPattern_x_y::ap_const_boolean_1 = true;

calcHaarPattern_x_y::calcHaarPattern_x_y(sc_module_name name) : sc_module(name), mVcdFile(0) {
    surf_Simplified_mbkb_U22 = new surf_Simplified_mbkb<1,1,16,11,16>("surf_Simplified_mbkb_U22");
    surf_Simplified_mbkb_U22->din0(tmp_133_reg_1070);
    surf_Simplified_mbkb_U22->din1(tmp_8_fu_935_p1);
    surf_Simplified_mbkb_U22->dout(tmp_8_fu_935_p2);
    surf_Simplified_mbkb_U23 = new surf_Simplified_mbkb<1,1,16,11,16>("surf_Simplified_mbkb_U23");
    surf_Simplified_mbkb_U23->din0(tmp_162_reg_1075);
    surf_Simplified_mbkb_U23->din1(tmp_20_fu_940_p1);
    surf_Simplified_mbkb_U23->dout(tmp_20_fu_940_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_Hi_assign_3_cast_fu_764_p1);
    sensitive << ( Hi_assign_3_reg_1044 );

    SC_METHOD(thread_Hi_assign_3_fu_634_p2);
    sensitive << ( tmp_15_cast_fu_630_p1 );

    SC_METHOD(thread_Hi_assign_cast_fu_653_p1);
    sensitive << ( Hi_assign_reg_1017 );

    SC_METHOD(thread_Hi_assign_fu_461_p2);
    sensitive << ( tmp_8_cast_fu_457_p1 );

    SC_METHOD(thread_Lo_assign_3_fu_774_p1);
    sensitive << ( tmp_17_fu_767_p3 );

    SC_METHOD(thread_Lo_assign_fu_663_p1);
    sensitive << ( tmp_7_fu_656_p3 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_277_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_277_p2 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_277_p2 );
    sensitive << ( p_Val2_16_reg_214 );
    sensitive << ( ap_return_preg );

    SC_METHOD(thread_box_0_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_73_cast_fu_298_p1 );

    SC_METHOD(thread_box_0_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_box_1_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_73_cast_fu_298_p1 );

    SC_METHOD(thread_box_1_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_box_2_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_73_cast_fu_298_p1 );

    SC_METHOD(thread_box_2_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_box_3_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_73_cast_fu_298_p1 );

    SC_METHOD(thread_box_3_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_box_4_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_73_cast_fu_298_p1 );

    SC_METHOD(thread_box_4_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_box_V_offset_cast_ca_fu_237_p1);
    sensitive << ( box_V_offset );

    SC_METHOD(thread_d_V_fu_930_p2);
    sensitive << ( r_V_s_reg_1126 );
    sensitive << ( p_Val2_16_reg_214 );

    SC_METHOD(thread_exitcond_fu_277_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( kn_reg_226 );

    SC_METHOD(thread_kn_1_fu_283_p2);
    sensitive << ( kn_reg_226 );

    SC_METHOD(thread_p_1_fu_424_p3);
    sensitive << ( ret_V_3_fu_390_p4 );
    sensitive << ( tmp_5_fu_412_p2 );
    sensitive << ( ret_V_4_fu_418_p2 );

    SC_METHOD(thread_p_2_fu_432_p3);
    sensitive << ( ret_V_3_fu_390_p4 );
    sensitive << ( p_Result_4_fu_400_p3 );
    sensitive << ( p_1_fu_424_p3 );

    SC_METHOD(thread_p_3_fu_597_p3);
    sensitive << ( ret_V_7_fu_563_p4 );
    sensitive << ( tmp_13_fu_585_p2 );
    sensitive << ( ret_V_8_fu_591_p2 );

    SC_METHOD(thread_p_4_fu_605_p3);
    sensitive << ( ret_V_7_fu_563_p4 );
    sensitive << ( p_Result_7_fu_573_p3 );
    sensitive << ( p_3_fu_597_p3 );

    SC_METHOD(thread_p_Result_4_fu_400_p3);
    sensitive << ( box_3_V_q0 );

    SC_METHOD(thread_p_Result_5_fu_754_p2);
    sensitive << ( tmp_130_fu_742_p2 );
    sensitive << ( tmp_131_fu_748_p2 );

    SC_METHOD(thread_p_Result_6_fu_490_p3);
    sensitive << ( box_0_V_q0 );

    SC_METHOD(thread_p_Result_7_fu_573_p3);
    sensitive << ( box_1_V_q0 );

    SC_METHOD(thread_p_Result_8_fu_865_p2);
    sensitive << ( tmp_159_fu_853_p2 );
    sensitive << ( tmp_160_fu_859_p2 );

    SC_METHOD(thread_p_Result_s_fu_317_p3);
    sensitive << ( box_2_V_q0 );

    SC_METHOD(thread_p_shl_cast_fu_249_p1);
    sensitive << ( tmp_fu_241_p3 );

    SC_METHOD(thread_r_V_s_fu_926_p2);
    sensitive << ( box_4_V_load_reg_1065 );
    sensitive << ( tmp_V_reg_1121 );

    SC_METHOD(thread_ret_V_2_fu_335_p2);
    sensitive << ( ret_V_fu_307_p4 );

    SC_METHOD(thread_ret_V_3_fu_390_p4);
    sensitive << ( box_3_V_q0 );

    SC_METHOD(thread_ret_V_4_fu_418_p2);
    sensitive << ( ret_V_3_fu_390_p4 );

    SC_METHOD(thread_ret_V_5_fu_480_p4);
    sensitive << ( box_0_V_q0 );

    SC_METHOD(thread_ret_V_6_fu_508_p2);
    sensitive << ( ret_V_5_fu_480_p4 );

    SC_METHOD(thread_ret_V_7_fu_563_p4);
    sensitive << ( box_1_V_q0 );

    SC_METHOD(thread_ret_V_8_fu_591_p2);
    sensitive << ( ret_V_7_fu_563_p4 );

    SC_METHOD(thread_ret_V_fu_307_p4);
    sensitive << ( box_2_V_q0 );

    SC_METHOD(thread_sumBuf_address0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_77_cast_fu_879_p1 );
    sensitive << ( tmp_82_cast_fu_901_p1 );

    SC_METHOD(thread_sumBuf_address1);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_78_cast_fu_888_p1 );
    sensitive << ( tmp_83_cast_fu_905_p1 );

    SC_METHOD(thread_sumBuf_ce0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_sumBuf_ce1);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_tmp_106_fu_325_p1);
    sensitive << ( box_2_V_q0 );

    SC_METHOD(thread_tmp_107_fu_341_p1);
    sensitive << ( cOffset );

    SC_METHOD(thread_tmp_108_fu_344_p4);
    sensitive << ( box_2_V_q0 );

    SC_METHOD(thread_tmp_109_fu_354_p1);
    sensitive << ( ret_V_2_fu_335_p2 );

    SC_METHOD(thread_tmp_10_fu_502_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_135_fu_498_p1 );

    SC_METHOD(thread_tmp_110_fu_358_p3);
    sensitive << ( tmp_2_fu_329_p2 );
    sensitive << ( tmp_108_fu_344_p4 );
    sensitive << ( tmp_109_fu_354_p1 );

    SC_METHOD(thread_tmp_111_fu_366_p4);
    sensitive << ( box_2_V_q0 );

    SC_METHOD(thread_tmp_112_fu_376_p3);
    sensitive << ( p_Result_s_fu_317_p3 );
    sensitive << ( tmp_110_fu_358_p3 );
    sensitive << ( tmp_111_fu_366_p4 );

    SC_METHOD(thread_tmp_113_fu_384_p2);
    sensitive << ( tmp_107_fu_341_p1 );
    sensitive << ( tmp_112_fu_376_p3 );

    SC_METHOD(thread_tmp_115_fu_408_p1);
    sensitive << ( box_3_V_q0 );

    SC_METHOD(thread_tmp_116_fu_472_p1);
    sensitive << ( tmp_9_fu_467_p2 );

    SC_METHOD(thread_tmp_117_fu_667_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( Lo_assign_fu_663_p1 );
    sensitive << ( Hi_assign_cast_fu_653_p1 );

    SC_METHOD(thread_tmp_118_fu_673_p3);
    sensitive << ( tmp_116_reg_1027 );

    SC_METHOD(thread_tmp_119_fu_476_p1);
    sensitive << ( Hi_assign_fu_461_p2 );

    SC_METHOD(thread_tmp_11_fu_875_p2);
    sensitive << ( tmp_113_reg_1011 );
    sensitive << ( tmp_8_reg_1080 );

    SC_METHOD(thread_tmp_120_fu_680_p4);
    sensitive << ( sumBufIndex_V );

    SC_METHOD(thread_tmp_121_fu_689_p2);
    sensitive << ( tmp_119_reg_1032 );
    sensitive << ( tmp_118_fu_673_p3 );

    SC_METHOD(thread_tmp_122_fu_694_p2);
    sensitive << ( tmp_118_fu_673_p3 );

    SC_METHOD(thread_tmp_123_fu_700_p2);
    sensitive << ( tmp_119_reg_1032 );
    sensitive << ( tmp_118_fu_673_p3 );

    SC_METHOD(thread_tmp_124_fu_705_p3);
    sensitive << ( tmp_117_fu_667_p2 );
    sensitive << ( tmp_121_fu_689_p2 );
    sensitive << ( tmp_123_fu_700_p2 );

    SC_METHOD(thread_tmp_125_fu_713_p3);
    sensitive << ( sumBufIndex_V );
    sensitive << ( tmp_117_fu_667_p2 );
    sensitive << ( tmp_120_fu_680_p4 );

    SC_METHOD(thread_tmp_126_fu_720_p3);
    sensitive << ( tmp_118_fu_673_p3 );
    sensitive << ( tmp_117_fu_667_p2 );
    sensitive << ( tmp_122_fu_694_p2 );

    SC_METHOD(thread_tmp_127_fu_728_p2);
    sensitive << ( tmp_124_fu_705_p3 );

    SC_METHOD(thread_tmp_128_fu_734_p1);
    sensitive << ( tmp_126_fu_720_p3 );

    SC_METHOD(thread_tmp_129_fu_738_p1);
    sensitive << ( tmp_127_fu_728_p2 );

    SC_METHOD(thread_tmp_12_fu_884_p2);
    sensitive << ( tmp_142_reg_1038 );
    sensitive << ( tmp_8_reg_1080 );

    SC_METHOD(thread_tmp_130_fu_742_p2);
    sensitive << ( tmp_125_fu_713_p3 );
    sensitive << ( tmp_128_fu_734_p1 );

    SC_METHOD(thread_tmp_131_fu_748_p2);
    sensitive << ( tmp_129_fu_738_p1 );

    SC_METHOD(thread_tmp_133_fu_760_p1);
    sensitive << ( p_Result_5_fu_754_p2 );

    SC_METHOD(thread_tmp_135_fu_498_p1);
    sensitive << ( box_0_V_q0 );

    SC_METHOD(thread_tmp_136_fu_514_p1);
    sensitive << ( cOffset );

    SC_METHOD(thread_tmp_137_fu_517_p4);
    sensitive << ( box_0_V_q0 );

    SC_METHOD(thread_tmp_138_fu_527_p1);
    sensitive << ( ret_V_6_fu_508_p2 );

    SC_METHOD(thread_tmp_139_fu_531_p3);
    sensitive << ( tmp_10_fu_502_p2 );
    sensitive << ( tmp_137_fu_517_p4 );
    sensitive << ( tmp_138_fu_527_p1 );

    SC_METHOD(thread_tmp_13_fu_585_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_144_fu_581_p1 );

    SC_METHOD(thread_tmp_140_fu_539_p4);
    sensitive << ( box_0_V_q0 );

    SC_METHOD(thread_tmp_141_fu_549_p3);
    sensitive << ( p_Result_6_fu_490_p3 );
    sensitive << ( tmp_139_fu_531_p3 );
    sensitive << ( tmp_140_fu_539_p4 );

    SC_METHOD(thread_tmp_142_fu_557_p2);
    sensitive << ( tmp_136_fu_514_p1 );
    sensitive << ( tmp_141_fu_549_p3 );

    SC_METHOD(thread_tmp_144_fu_581_p1);
    sensitive << ( box_1_V_q0 );

    SC_METHOD(thread_tmp_145_fu_645_p1);
    sensitive << ( tmp_16_fu_640_p2 );

    SC_METHOD(thread_tmp_146_fu_778_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( Lo_assign_3_fu_774_p1 );
    sensitive << ( Hi_assign_3_cast_fu_764_p1 );

    SC_METHOD(thread_tmp_147_fu_784_p3);
    sensitive << ( tmp_145_reg_1054 );

    SC_METHOD(thread_tmp_148_fu_649_p1);
    sensitive << ( Hi_assign_3_fu_634_p2 );

    SC_METHOD(thread_tmp_149_fu_791_p4);
    sensitive << ( sumBufIndex_V );

    SC_METHOD(thread_tmp_14_fu_617_p2);
    sensitive << ( tmp_22_cast_reg_972 );
    sensitive << ( tmp_53_cast_fu_613_p1 );

    SC_METHOD(thread_tmp_150_fu_800_p2);
    sensitive << ( tmp_148_reg_1059 );
    sensitive << ( tmp_147_fu_784_p3 );

    SC_METHOD(thread_tmp_151_fu_805_p2);
    sensitive << ( tmp_147_fu_784_p3 );

    SC_METHOD(thread_tmp_152_fu_811_p2);
    sensitive << ( tmp_148_reg_1059 );
    sensitive << ( tmp_147_fu_784_p3 );

    SC_METHOD(thread_tmp_153_fu_816_p3);
    sensitive << ( tmp_146_fu_778_p2 );
    sensitive << ( tmp_150_fu_800_p2 );
    sensitive << ( tmp_152_fu_811_p2 );

    SC_METHOD(thread_tmp_154_fu_824_p3);
    sensitive << ( sumBufIndex_V );
    sensitive << ( tmp_146_fu_778_p2 );
    sensitive << ( tmp_149_fu_791_p4 );

    SC_METHOD(thread_tmp_155_fu_831_p3);
    sensitive << ( tmp_147_fu_784_p3 );
    sensitive << ( tmp_146_fu_778_p2 );
    sensitive << ( tmp_151_fu_805_p2 );

    SC_METHOD(thread_tmp_156_fu_839_p2);
    sensitive << ( tmp_153_fu_816_p3 );

    SC_METHOD(thread_tmp_157_fu_845_p1);
    sensitive << ( tmp_155_fu_831_p3 );

    SC_METHOD(thread_tmp_158_fu_849_p1);
    sensitive << ( tmp_156_fu_839_p2 );

    SC_METHOD(thread_tmp_159_fu_853_p2);
    sensitive << ( tmp_154_fu_824_p3 );
    sensitive << ( tmp_157_fu_845_p1 );

    SC_METHOD(thread_tmp_15_cast_fu_630_p1);
    sensitive << ( tmp_15_fu_622_p3 );

    SC_METHOD(thread_tmp_15_fu_622_p3);
    sensitive << ( tmp_14_fu_617_p2 );

    SC_METHOD(thread_tmp_160_fu_859_p2);
    sensitive << ( tmp_158_fu_849_p1 );

    SC_METHOD(thread_tmp_162_fu_871_p1);
    sensitive << ( p_Result_8_fu_865_p2 );

    SC_METHOD(thread_tmp_16_fu_640_p2);
    sensitive << ( tmp_cast1_reg_966 );
    sensitive << ( tmp_53_cast_fu_613_p1 );

    SC_METHOD(thread_tmp_17_fu_767_p3);
    sensitive << ( tmp_16_reg_1049 );

    SC_METHOD(thread_tmp_18_fu_909_p2);
    sensitive << ( sumBuf_q0 );
    sensitive << ( sumBuf_q1 );

    SC_METHOD(thread_tmp_19_fu_915_p2);
    sensitive << ( sumBuf_q0 );
    sensitive << ( tmp_18_reg_1116 );

    SC_METHOD(thread_tmp_1_fu_267_p2);
    sensitive << ( tmp_cast_fu_263_p1 );

    SC_METHOD(thread_tmp_20_fu_940_p1);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_tmp_21_fu_893_p2);
    sensitive << ( tmp_113_reg_1011 );
    sensitive << ( tmp_20_fu_940_p2 );

    SC_METHOD(thread_tmp_22_cast_fu_273_p1);
    sensitive << ( tmp_1_fu_267_p2 );

    SC_METHOD(thread_tmp_22_fu_897_p2);
    sensitive << ( tmp_142_reg_1038 );
    sensitive << ( tmp_20_fu_940_p2 );

    SC_METHOD(thread_tmp_27_cast_fu_440_p1);
    sensitive << ( p_2_fu_432_p3 );

    SC_METHOD(thread_tmp_2_fu_329_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_106_fu_325_p1 );

    SC_METHOD(thread_tmp_3_fu_293_p2);
    sensitive << ( tmp_s_reg_961 );
    sensitive << ( tmp_cast_41_fu_289_p1 );

    SC_METHOD(thread_tmp_4_fu_449_p3);
    sensitive << ( tmp_6_fu_444_p2 );

    SC_METHOD(thread_tmp_53_cast_fu_613_p1);
    sensitive << ( p_4_fu_605_p3 );

    SC_METHOD(thread_tmp_5_fu_412_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_115_fu_408_p1 );

    SC_METHOD(thread_tmp_6_fu_444_p2);
    sensitive << ( tmp_22_cast_reg_972 );
    sensitive << ( tmp_27_cast_fu_440_p1 );

    SC_METHOD(thread_tmp_73_cast_fu_298_p1);
    sensitive << ( tmp_3_fu_293_p2 );

    SC_METHOD(thread_tmp_77_cast_fu_879_p1);
    sensitive << ( tmp_11_fu_875_p2 );

    SC_METHOD(thread_tmp_78_cast_fu_888_p1);
    sensitive << ( tmp_12_fu_884_p2 );

    SC_METHOD(thread_tmp_7_fu_656_p3);
    sensitive << ( tmp_9_reg_1022 );

    SC_METHOD(thread_tmp_82_cast_fu_901_p1);
    sensitive << ( tmp_21_reg_1096 );

    SC_METHOD(thread_tmp_83_cast_fu_905_p1);
    sensitive << ( tmp_22_reg_1101 );

    SC_METHOD(thread_tmp_8_cast_fu_457_p1);
    sensitive << ( tmp_4_fu_449_p3 );

    SC_METHOD(thread_tmp_8_fu_935_p1);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_tmp_9_fu_467_p2);
    sensitive << ( tmp_cast1_reg_966 );
    sensitive << ( tmp_27_cast_fu_440_p1 );

    SC_METHOD(thread_tmp_V_fu_920_p2);
    sensitive << ( sumBuf_q1 );
    sensitive << ( tmp_19_fu_915_p2 );

    SC_METHOD(thread_tmp_cast1_fu_259_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( rOffset );

    SC_METHOD(thread_tmp_cast1_fu_259_p1);
    sensitive << ( tmp_cast1_fu_259_p0 );

    SC_METHOD(thread_tmp_cast_41_fu_289_p1);
    sensitive << ( kn_reg_226 );

    SC_METHOD(thread_tmp_cast_fu_263_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( rOffset );

    SC_METHOD(thread_tmp_cast_fu_263_p1);
    sensitive << ( tmp_cast_fu_263_p0 );

    SC_METHOD(thread_tmp_fu_241_p3);
    sensitive << ( box_V_offset );

    SC_METHOD(thread_tmp_s_fu_253_p2);
    sensitive << ( p_shl_cast_fu_249_p1 );
    sensitive << ( box_V_offset_cast_ca_fu_237_p1 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_fu_277_p2 );

    ap_CS_fsm = "0000000001";
    ap_return_preg = "00000000000000000000000000000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "calcHaarPattern_x_y_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, sumBuf_address0, "(port)sumBuf_address0");
    sc_trace(mVcdFile, sumBuf_ce0, "(port)sumBuf_ce0");
    sc_trace(mVcdFile, sumBuf_q0, "(port)sumBuf_q0");
    sc_trace(mVcdFile, sumBuf_address1, "(port)sumBuf_address1");
    sc_trace(mVcdFile, sumBuf_ce1, "(port)sumBuf_ce1");
    sc_trace(mVcdFile, sumBuf_q1, "(port)sumBuf_q1");
    sc_trace(mVcdFile, box_0_V_address0, "(port)box_0_V_address0");
    sc_trace(mVcdFile, box_0_V_ce0, "(port)box_0_V_ce0");
    sc_trace(mVcdFile, box_0_V_q0, "(port)box_0_V_q0");
    sc_trace(mVcdFile, box_1_V_address0, "(port)box_1_V_address0");
    sc_trace(mVcdFile, box_1_V_ce0, "(port)box_1_V_ce0");
    sc_trace(mVcdFile, box_1_V_q0, "(port)box_1_V_q0");
    sc_trace(mVcdFile, box_2_V_address0, "(port)box_2_V_address0");
    sc_trace(mVcdFile, box_2_V_ce0, "(port)box_2_V_ce0");
    sc_trace(mVcdFile, box_2_V_q0, "(port)box_2_V_q0");
    sc_trace(mVcdFile, box_3_V_address0, "(port)box_3_V_address0");
    sc_trace(mVcdFile, box_3_V_ce0, "(port)box_3_V_ce0");
    sc_trace(mVcdFile, box_3_V_q0, "(port)box_3_V_q0");
    sc_trace(mVcdFile, box_4_V_address0, "(port)box_4_V_address0");
    sc_trace(mVcdFile, box_4_V_ce0, "(port)box_4_V_ce0");
    sc_trace(mVcdFile, box_4_V_q0, "(port)box_4_V_q0");
    sc_trace(mVcdFile, box_V_offset, "(port)box_V_offset");
    sc_trace(mVcdFile, sumBufIndex_V, "(port)sumBufIndex_V");
    sc_trace(mVcdFile, rOffset, "(port)rOffset");
    sc_trace(mVcdFile, cOffset, "(port)cOffset");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, tmp_s_fu_253_p2, "tmp_s_fu_253_p2");
    sc_trace(mVcdFile, tmp_s_reg_961, "tmp_s_reg_961");
    sc_trace(mVcdFile, tmp_cast1_fu_259_p1, "tmp_cast1_fu_259_p1");
    sc_trace(mVcdFile, tmp_cast1_reg_966, "tmp_cast1_reg_966");
    sc_trace(mVcdFile, tmp_22_cast_fu_273_p1, "tmp_22_cast_fu_273_p1");
    sc_trace(mVcdFile, tmp_22_cast_reg_972, "tmp_22_cast_reg_972");
    sc_trace(mVcdFile, kn_1_fu_283_p2, "kn_1_fu_283_p2");
    sc_trace(mVcdFile, kn_1_reg_981, "kn_1_reg_981");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, exitcond_fu_277_p2, "exitcond_fu_277_p2");
    sc_trace(mVcdFile, tmp_113_fu_384_p2, "tmp_113_fu_384_p2");
    sc_trace(mVcdFile, tmp_113_reg_1011, "tmp_113_reg_1011");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, Hi_assign_fu_461_p2, "Hi_assign_fu_461_p2");
    sc_trace(mVcdFile, Hi_assign_reg_1017, "Hi_assign_reg_1017");
    sc_trace(mVcdFile, tmp_9_fu_467_p2, "tmp_9_fu_467_p2");
    sc_trace(mVcdFile, tmp_9_reg_1022, "tmp_9_reg_1022");
    sc_trace(mVcdFile, tmp_116_fu_472_p1, "tmp_116_fu_472_p1");
    sc_trace(mVcdFile, tmp_116_reg_1027, "tmp_116_reg_1027");
    sc_trace(mVcdFile, tmp_119_fu_476_p1, "tmp_119_fu_476_p1");
    sc_trace(mVcdFile, tmp_119_reg_1032, "tmp_119_reg_1032");
    sc_trace(mVcdFile, tmp_142_fu_557_p2, "tmp_142_fu_557_p2");
    sc_trace(mVcdFile, tmp_142_reg_1038, "tmp_142_reg_1038");
    sc_trace(mVcdFile, Hi_assign_3_fu_634_p2, "Hi_assign_3_fu_634_p2");
    sc_trace(mVcdFile, Hi_assign_3_reg_1044, "Hi_assign_3_reg_1044");
    sc_trace(mVcdFile, tmp_16_fu_640_p2, "tmp_16_fu_640_p2");
    sc_trace(mVcdFile, tmp_16_reg_1049, "tmp_16_reg_1049");
    sc_trace(mVcdFile, tmp_145_fu_645_p1, "tmp_145_fu_645_p1");
    sc_trace(mVcdFile, tmp_145_reg_1054, "tmp_145_reg_1054");
    sc_trace(mVcdFile, tmp_148_fu_649_p1, "tmp_148_fu_649_p1");
    sc_trace(mVcdFile, tmp_148_reg_1059, "tmp_148_reg_1059");
    sc_trace(mVcdFile, box_4_V_load_reg_1065, "box_4_V_load_reg_1065");
    sc_trace(mVcdFile, tmp_133_fu_760_p1, "tmp_133_fu_760_p1");
    sc_trace(mVcdFile, tmp_133_reg_1070, "tmp_133_reg_1070");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, tmp_162_fu_871_p1, "tmp_162_fu_871_p1");
    sc_trace(mVcdFile, tmp_162_reg_1075, "tmp_162_reg_1075");
    sc_trace(mVcdFile, tmp_8_fu_935_p2, "tmp_8_fu_935_p2");
    sc_trace(mVcdFile, tmp_8_reg_1080, "tmp_8_reg_1080");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, tmp_21_fu_893_p2, "tmp_21_fu_893_p2");
    sc_trace(mVcdFile, tmp_21_reg_1096, "tmp_21_reg_1096");
    sc_trace(mVcdFile, tmp_22_fu_897_p2, "tmp_22_fu_897_p2");
    sc_trace(mVcdFile, tmp_22_reg_1101, "tmp_22_reg_1101");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, tmp_18_fu_909_p2, "tmp_18_fu_909_p2");
    sc_trace(mVcdFile, tmp_18_reg_1116, "tmp_18_reg_1116");
    sc_trace(mVcdFile, tmp_V_fu_920_p2, "tmp_V_fu_920_p2");
    sc_trace(mVcdFile, tmp_V_reg_1121, "tmp_V_reg_1121");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, r_V_s_fu_926_p2, "r_V_s_fu_926_p2");
    sc_trace(mVcdFile, r_V_s_reg_1126, "r_V_s_reg_1126");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, d_V_fu_930_p2, "d_V_fu_930_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, p_Val2_16_reg_214, "p_Val2_16_reg_214");
    sc_trace(mVcdFile, kn_reg_226, "kn_reg_226");
    sc_trace(mVcdFile, tmp_73_cast_fu_298_p1, "tmp_73_cast_fu_298_p1");
    sc_trace(mVcdFile, tmp_77_cast_fu_879_p1, "tmp_77_cast_fu_879_p1");
    sc_trace(mVcdFile, tmp_78_cast_fu_888_p1, "tmp_78_cast_fu_888_p1");
    sc_trace(mVcdFile, tmp_82_cast_fu_901_p1, "tmp_82_cast_fu_901_p1");
    sc_trace(mVcdFile, tmp_83_cast_fu_905_p1, "tmp_83_cast_fu_905_p1");
    sc_trace(mVcdFile, tmp_fu_241_p3, "tmp_fu_241_p3");
    sc_trace(mVcdFile, p_shl_cast_fu_249_p1, "p_shl_cast_fu_249_p1");
    sc_trace(mVcdFile, box_V_offset_cast_ca_fu_237_p1, "box_V_offset_cast_ca_fu_237_p1");
    sc_trace(mVcdFile, tmp_cast1_fu_259_p0, "tmp_cast1_fu_259_p0");
    sc_trace(mVcdFile, tmp_cast_fu_263_p0, "tmp_cast_fu_263_p0");
    sc_trace(mVcdFile, tmp_cast_fu_263_p1, "tmp_cast_fu_263_p1");
    sc_trace(mVcdFile, tmp_1_fu_267_p2, "tmp_1_fu_267_p2");
    sc_trace(mVcdFile, tmp_cast_41_fu_289_p1, "tmp_cast_41_fu_289_p1");
    sc_trace(mVcdFile, tmp_3_fu_293_p2, "tmp_3_fu_293_p2");
    sc_trace(mVcdFile, tmp_106_fu_325_p1, "tmp_106_fu_325_p1");
    sc_trace(mVcdFile, ret_V_fu_307_p4, "ret_V_fu_307_p4");
    sc_trace(mVcdFile, ret_V_2_fu_335_p2, "ret_V_2_fu_335_p2");
    sc_trace(mVcdFile, tmp_2_fu_329_p2, "tmp_2_fu_329_p2");
    sc_trace(mVcdFile, tmp_108_fu_344_p4, "tmp_108_fu_344_p4");
    sc_trace(mVcdFile, tmp_109_fu_354_p1, "tmp_109_fu_354_p1");
    sc_trace(mVcdFile, p_Result_s_fu_317_p3, "p_Result_s_fu_317_p3");
    sc_trace(mVcdFile, tmp_110_fu_358_p3, "tmp_110_fu_358_p3");
    sc_trace(mVcdFile, tmp_111_fu_366_p4, "tmp_111_fu_366_p4");
    sc_trace(mVcdFile, tmp_107_fu_341_p1, "tmp_107_fu_341_p1");
    sc_trace(mVcdFile, tmp_112_fu_376_p3, "tmp_112_fu_376_p3");
    sc_trace(mVcdFile, tmp_115_fu_408_p1, "tmp_115_fu_408_p1");
    sc_trace(mVcdFile, ret_V_3_fu_390_p4, "ret_V_3_fu_390_p4");
    sc_trace(mVcdFile, tmp_5_fu_412_p2, "tmp_5_fu_412_p2");
    sc_trace(mVcdFile, ret_V_4_fu_418_p2, "ret_V_4_fu_418_p2");
    sc_trace(mVcdFile, p_Result_4_fu_400_p3, "p_Result_4_fu_400_p3");
    sc_trace(mVcdFile, p_1_fu_424_p3, "p_1_fu_424_p3");
    sc_trace(mVcdFile, p_2_fu_432_p3, "p_2_fu_432_p3");
    sc_trace(mVcdFile, tmp_27_cast_fu_440_p1, "tmp_27_cast_fu_440_p1");
    sc_trace(mVcdFile, tmp_6_fu_444_p2, "tmp_6_fu_444_p2");
    sc_trace(mVcdFile, tmp_4_fu_449_p3, "tmp_4_fu_449_p3");
    sc_trace(mVcdFile, tmp_8_cast_fu_457_p1, "tmp_8_cast_fu_457_p1");
    sc_trace(mVcdFile, tmp_135_fu_498_p1, "tmp_135_fu_498_p1");
    sc_trace(mVcdFile, ret_V_5_fu_480_p4, "ret_V_5_fu_480_p4");
    sc_trace(mVcdFile, ret_V_6_fu_508_p2, "ret_V_6_fu_508_p2");
    sc_trace(mVcdFile, tmp_10_fu_502_p2, "tmp_10_fu_502_p2");
    sc_trace(mVcdFile, tmp_137_fu_517_p4, "tmp_137_fu_517_p4");
    sc_trace(mVcdFile, tmp_138_fu_527_p1, "tmp_138_fu_527_p1");
    sc_trace(mVcdFile, p_Result_6_fu_490_p3, "p_Result_6_fu_490_p3");
    sc_trace(mVcdFile, tmp_139_fu_531_p3, "tmp_139_fu_531_p3");
    sc_trace(mVcdFile, tmp_140_fu_539_p4, "tmp_140_fu_539_p4");
    sc_trace(mVcdFile, tmp_136_fu_514_p1, "tmp_136_fu_514_p1");
    sc_trace(mVcdFile, tmp_141_fu_549_p3, "tmp_141_fu_549_p3");
    sc_trace(mVcdFile, tmp_144_fu_581_p1, "tmp_144_fu_581_p1");
    sc_trace(mVcdFile, ret_V_7_fu_563_p4, "ret_V_7_fu_563_p4");
    sc_trace(mVcdFile, tmp_13_fu_585_p2, "tmp_13_fu_585_p2");
    sc_trace(mVcdFile, ret_V_8_fu_591_p2, "ret_V_8_fu_591_p2");
    sc_trace(mVcdFile, p_Result_7_fu_573_p3, "p_Result_7_fu_573_p3");
    sc_trace(mVcdFile, p_3_fu_597_p3, "p_3_fu_597_p3");
    sc_trace(mVcdFile, p_4_fu_605_p3, "p_4_fu_605_p3");
    sc_trace(mVcdFile, tmp_53_cast_fu_613_p1, "tmp_53_cast_fu_613_p1");
    sc_trace(mVcdFile, tmp_14_fu_617_p2, "tmp_14_fu_617_p2");
    sc_trace(mVcdFile, tmp_15_fu_622_p3, "tmp_15_fu_622_p3");
    sc_trace(mVcdFile, tmp_15_cast_fu_630_p1, "tmp_15_cast_fu_630_p1");
    sc_trace(mVcdFile, tmp_7_fu_656_p3, "tmp_7_fu_656_p3");
    sc_trace(mVcdFile, Lo_assign_fu_663_p1, "Lo_assign_fu_663_p1");
    sc_trace(mVcdFile, Hi_assign_cast_fu_653_p1, "Hi_assign_cast_fu_653_p1");
    sc_trace(mVcdFile, tmp_118_fu_673_p3, "tmp_118_fu_673_p3");
    sc_trace(mVcdFile, tmp_117_fu_667_p2, "tmp_117_fu_667_p2");
    sc_trace(mVcdFile, tmp_121_fu_689_p2, "tmp_121_fu_689_p2");
    sc_trace(mVcdFile, tmp_123_fu_700_p2, "tmp_123_fu_700_p2");
    sc_trace(mVcdFile, tmp_120_fu_680_p4, "tmp_120_fu_680_p4");
    sc_trace(mVcdFile, tmp_122_fu_694_p2, "tmp_122_fu_694_p2");
    sc_trace(mVcdFile, tmp_124_fu_705_p3, "tmp_124_fu_705_p3");
    sc_trace(mVcdFile, tmp_126_fu_720_p3, "tmp_126_fu_720_p3");
    sc_trace(mVcdFile, tmp_127_fu_728_p2, "tmp_127_fu_728_p2");
    sc_trace(mVcdFile, tmp_125_fu_713_p3, "tmp_125_fu_713_p3");
    sc_trace(mVcdFile, tmp_128_fu_734_p1, "tmp_128_fu_734_p1");
    sc_trace(mVcdFile, tmp_129_fu_738_p1, "tmp_129_fu_738_p1");
    sc_trace(mVcdFile, tmp_130_fu_742_p2, "tmp_130_fu_742_p2");
    sc_trace(mVcdFile, tmp_131_fu_748_p2, "tmp_131_fu_748_p2");
    sc_trace(mVcdFile, p_Result_5_fu_754_p2, "p_Result_5_fu_754_p2");
    sc_trace(mVcdFile, tmp_17_fu_767_p3, "tmp_17_fu_767_p3");
    sc_trace(mVcdFile, Lo_assign_3_fu_774_p1, "Lo_assign_3_fu_774_p1");
    sc_trace(mVcdFile, Hi_assign_3_cast_fu_764_p1, "Hi_assign_3_cast_fu_764_p1");
    sc_trace(mVcdFile, tmp_147_fu_784_p3, "tmp_147_fu_784_p3");
    sc_trace(mVcdFile, tmp_146_fu_778_p2, "tmp_146_fu_778_p2");
    sc_trace(mVcdFile, tmp_150_fu_800_p2, "tmp_150_fu_800_p2");
    sc_trace(mVcdFile, tmp_152_fu_811_p2, "tmp_152_fu_811_p2");
    sc_trace(mVcdFile, tmp_149_fu_791_p4, "tmp_149_fu_791_p4");
    sc_trace(mVcdFile, tmp_151_fu_805_p2, "tmp_151_fu_805_p2");
    sc_trace(mVcdFile, tmp_153_fu_816_p3, "tmp_153_fu_816_p3");
    sc_trace(mVcdFile, tmp_155_fu_831_p3, "tmp_155_fu_831_p3");
    sc_trace(mVcdFile, tmp_156_fu_839_p2, "tmp_156_fu_839_p2");
    sc_trace(mVcdFile, tmp_154_fu_824_p3, "tmp_154_fu_824_p3");
    sc_trace(mVcdFile, tmp_157_fu_845_p1, "tmp_157_fu_845_p1");
    sc_trace(mVcdFile, tmp_158_fu_849_p1, "tmp_158_fu_849_p1");
    sc_trace(mVcdFile, tmp_159_fu_853_p2, "tmp_159_fu_853_p2");
    sc_trace(mVcdFile, tmp_160_fu_859_p2, "tmp_160_fu_859_p2");
    sc_trace(mVcdFile, p_Result_8_fu_865_p2, "p_Result_8_fu_865_p2");
    sc_trace(mVcdFile, tmp_11_fu_875_p2, "tmp_11_fu_875_p2");
    sc_trace(mVcdFile, tmp_12_fu_884_p2, "tmp_12_fu_884_p2");
    sc_trace(mVcdFile, tmp_20_fu_940_p2, "tmp_20_fu_940_p2");
    sc_trace(mVcdFile, tmp_19_fu_915_p2, "tmp_19_fu_915_p2");
    sc_trace(mVcdFile, tmp_8_fu_935_p1, "tmp_8_fu_935_p1");
    sc_trace(mVcdFile, tmp_20_fu_940_p1, "tmp_20_fu_940_p1");
    sc_trace(mVcdFile, ap_return_preg, "ap_return_preg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

calcHaarPattern_x_y::~calcHaarPattern_x_y() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete surf_Simplified_mbkb_U22;
    delete surf_Simplified_mbkb_U23;
}

void calcHaarPattern_x_y::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_preg = ap_const_lv32_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
             esl_seteq<1,1,1>(exitcond_fu_277_p2.read(), ap_const_lv1_1))) {
            ap_return_preg = p_Val2_16_reg_214.read();
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        kn_reg_226 = kn_1_reg_981.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        kn_reg_226 = ap_const_lv2_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        p_Val2_16_reg_214 = d_V_fu_930_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        p_Val2_16_reg_214 = ap_const_lv32_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        Hi_assign_3_reg_1044 = Hi_assign_3_fu_634_p2.read();
        Hi_assign_reg_1017 = Hi_assign_fu_461_p2.read();
        box_4_V_load_reg_1065 = box_4_V_q0.read();
        tmp_113_reg_1011 = tmp_113_fu_384_p2.read();
        tmp_116_reg_1027 = tmp_116_fu_472_p1.read();
        tmp_119_reg_1032 = tmp_119_fu_476_p1.read();
        tmp_142_reg_1038 = tmp_142_fu_557_p2.read();
        tmp_145_reg_1054 = tmp_145_fu_645_p1.read();
        tmp_148_reg_1059 = tmp_148_fu_649_p1.read();
        tmp_16_reg_1049 = tmp_16_fu_640_p2.read();
        tmp_9_reg_1022 = tmp_9_fu_467_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        kn_1_reg_981 = kn_1_fu_283_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        r_V_s_reg_1126 = r_V_s_fu_926_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        tmp_133_reg_1070 = tmp_133_fu_760_p1.read();
        tmp_162_reg_1075 = tmp_162_fu_871_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        tmp_18_reg_1116 = tmp_18_fu_909_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        tmp_21_reg_1096 = tmp_21_fu_893_p2.read();
        tmp_22_reg_1101 = tmp_22_fu_897_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        tmp_22_cast_reg_972 = tmp_22_cast_fu_273_p1.read();
        tmp_cast1_reg_966 = tmp_cast1_fu_259_p1.read();
        tmp_s_reg_961 = tmp_s_fu_253_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        tmp_8_reg_1080 = tmp_8_fu_935_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        tmp_V_reg_1121 = tmp_V_fu_920_p2.read();
    }
}

void calcHaarPattern_x_y::thread_Hi_assign_3_cast_fu_764_p1() {
    Hi_assign_3_cast_fu_764_p1 = esl_sext<32,27>(Hi_assign_3_reg_1044.read());
}

void calcHaarPattern_x_y::thread_Hi_assign_3_fu_634_p2() {
    Hi_assign_3_fu_634_p2 = (!tmp_15_cast_fu_630_p1.read().is_01() || !ap_const_lv27_7FFFFFF.is_01())? sc_lv<27>(): (sc_bigint<27>(tmp_15_cast_fu_630_p1.read()) + sc_bigint<27>(ap_const_lv27_7FFFFFF));
}

void calcHaarPattern_x_y::thread_Hi_assign_cast_fu_653_p1() {
    Hi_assign_cast_fu_653_p1 = esl_sext<32,27>(Hi_assign_reg_1017.read());
}

void calcHaarPattern_x_y::thread_Hi_assign_fu_461_p2() {
    Hi_assign_fu_461_p2 = (!tmp_8_cast_fu_457_p1.read().is_01() || !ap_const_lv27_7FFFFFF.is_01())? sc_lv<27>(): (sc_bigint<27>(tmp_8_cast_fu_457_p1.read()) + sc_bigint<27>(ap_const_lv27_7FFFFFF));
}

void calcHaarPattern_x_y::thread_Lo_assign_3_fu_774_p1() {
    Lo_assign_3_fu_774_p1 = esl_sext<32,26>(tmp_17_fu_767_p3.read());
}

void calcHaarPattern_x_y::thread_Lo_assign_fu_663_p1() {
    Lo_assign_fu_663_p1 = esl_sext<32,26>(tmp_7_fu_656_p3.read());
}

void calcHaarPattern_x_y::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void calcHaarPattern_x_y::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void calcHaarPattern_x_y::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void calcHaarPattern_x_y::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void calcHaarPattern_x_y::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void calcHaarPattern_x_y::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void calcHaarPattern_x_y::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void calcHaarPattern_x_y::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void calcHaarPattern_x_y::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void calcHaarPattern_x_y::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void calcHaarPattern_x_y::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(exitcond_fu_277_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void calcHaarPattern_x_y::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void calcHaarPattern_x_y::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_277_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void calcHaarPattern_x_y::thread_ap_return() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_277_p2.read(), ap_const_lv1_1))) {
        ap_return = p_Val2_16_reg_214.read();
    } else {
        ap_return = ap_return_preg.read();
    }
}

void calcHaarPattern_x_y::thread_box_0_V_address0() {
    box_0_V_address0 =  (sc_lv<4>) (tmp_73_cast_fu_298_p1.read());
}

void calcHaarPattern_x_y::thread_box_0_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        box_0_V_ce0 = ap_const_logic_1;
    } else {
        box_0_V_ce0 = ap_const_logic_0;
    }
}

void calcHaarPattern_x_y::thread_box_1_V_address0() {
    box_1_V_address0 =  (sc_lv<4>) (tmp_73_cast_fu_298_p1.read());
}

void calcHaarPattern_x_y::thread_box_1_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        box_1_V_ce0 = ap_const_logic_1;
    } else {
        box_1_V_ce0 = ap_const_logic_0;
    }
}

void calcHaarPattern_x_y::thread_box_2_V_address0() {
    box_2_V_address0 =  (sc_lv<4>) (tmp_73_cast_fu_298_p1.read());
}

void calcHaarPattern_x_y::thread_box_2_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        box_2_V_ce0 = ap_const_logic_1;
    } else {
        box_2_V_ce0 = ap_const_logic_0;
    }
}

void calcHaarPattern_x_y::thread_box_3_V_address0() {
    box_3_V_address0 =  (sc_lv<4>) (tmp_73_cast_fu_298_p1.read());
}

void calcHaarPattern_x_y::thread_box_3_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        box_3_V_ce0 = ap_const_logic_1;
    } else {
        box_3_V_ce0 = ap_const_logic_0;
    }
}

void calcHaarPattern_x_y::thread_box_4_V_address0() {
    box_4_V_address0 =  (sc_lv<4>) (tmp_73_cast_fu_298_p1.read());
}

void calcHaarPattern_x_y::thread_box_4_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        box_4_V_ce0 = ap_const_logic_1;
    } else {
        box_4_V_ce0 = ap_const_logic_0;
    }
}

void calcHaarPattern_x_y::thread_box_V_offset_cast_ca_fu_237_p1() {
    box_V_offset_cast_ca_fu_237_p1 = esl_zext<5,2>(box_V_offset.read());
}

void calcHaarPattern_x_y::thread_d_V_fu_930_p2() {
    d_V_fu_930_p2 = (!p_Val2_16_reg_214.read().is_01() || !r_V_s_reg_1126.read().is_01())? sc_lv<32>(): (sc_biguint<32>(p_Val2_16_reg_214.read()) + sc_biguint<32>(r_V_s_reg_1126.read()));
}

void calcHaarPattern_x_y::thread_exitcond_fu_277_p2() {
    exitcond_fu_277_p2 = (!kn_reg_226.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(kn_reg_226.read() == ap_const_lv2_3);
}

void calcHaarPattern_x_y::thread_kn_1_fu_283_p2() {
    kn_1_fu_283_p2 = (!kn_reg_226.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(kn_reg_226.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void calcHaarPattern_x_y::thread_p_1_fu_424_p3() {
    p_1_fu_424_p3 = (!tmp_5_fu_412_p2.read()[0].is_01())? sc_lv<22>(): ((tmp_5_fu_412_p2.read()[0].to_bool())? ret_V_3_fu_390_p4.read(): ret_V_4_fu_418_p2.read());
}

void calcHaarPattern_x_y::thread_p_2_fu_432_p3() {
    p_2_fu_432_p3 = (!p_Result_4_fu_400_p3.read()[0].is_01())? sc_lv<22>(): ((p_Result_4_fu_400_p3.read()[0].to_bool())? p_1_fu_424_p3.read(): ret_V_3_fu_390_p4.read());
}

void calcHaarPattern_x_y::thread_p_3_fu_597_p3() {
    p_3_fu_597_p3 = (!tmp_13_fu_585_p2.read()[0].is_01())? sc_lv<22>(): ((tmp_13_fu_585_p2.read()[0].to_bool())? ret_V_7_fu_563_p4.read(): ret_V_8_fu_591_p2.read());
}

void calcHaarPattern_x_y::thread_p_4_fu_605_p3() {
    p_4_fu_605_p3 = (!p_Result_7_fu_573_p3.read()[0].is_01())? sc_lv<22>(): ((p_Result_7_fu_573_p3.read()[0].to_bool())? p_3_fu_597_p3.read(): ret_V_7_fu_563_p4.read());
}

void calcHaarPattern_x_y::thread_p_Result_4_fu_400_p3() {
    p_Result_4_fu_400_p3 = box_3_V_q0.read().range(31, 31);
}

void calcHaarPattern_x_y::thread_p_Result_5_fu_754_p2() {
    p_Result_5_fu_754_p2 = (tmp_130_fu_742_p2.read() & tmp_131_fu_748_p2.read());
}

void calcHaarPattern_x_y::thread_p_Result_6_fu_490_p3() {
    p_Result_6_fu_490_p3 = box_0_V_q0.read().range(31, 31);
}

void calcHaarPattern_x_y::thread_p_Result_7_fu_573_p3() {
    p_Result_7_fu_573_p3 = box_1_V_q0.read().range(31, 31);
}

void calcHaarPattern_x_y::thread_p_Result_8_fu_865_p2() {
    p_Result_8_fu_865_p2 = (tmp_159_fu_853_p2.read() & tmp_160_fu_859_p2.read());
}

void calcHaarPattern_x_y::thread_p_Result_s_fu_317_p3() {
    p_Result_s_fu_317_p3 = box_2_V_q0.read().range(31, 31);
}

void calcHaarPattern_x_y::thread_p_shl_cast_fu_249_p1() {
    p_shl_cast_fu_249_p1 = esl_zext<5,4>(tmp_fu_241_p3.read());
}

void calcHaarPattern_x_y::thread_r_V_s_fu_926_p2() {
    r_V_s_fu_926_p2 = (!tmp_V_reg_1121.read().is_01() || !box_4_V_load_reg_1065.read().is_01())? sc_lv<32>(): sc_bigint<32>(tmp_V_reg_1121.read()) * sc_bigint<32>(box_4_V_load_reg_1065.read());
}

void calcHaarPattern_x_y::thread_ret_V_2_fu_335_p2() {
    ret_V_2_fu_335_p2 = (!ret_V_fu_307_p4.read().is_01() || !ap_const_lv22_1.is_01())? sc_lv<22>(): (sc_biguint<22>(ret_V_fu_307_p4.read()) + sc_biguint<22>(ap_const_lv22_1));
}

void calcHaarPattern_x_y::thread_ret_V_3_fu_390_p4() {
    ret_V_3_fu_390_p4 = box_3_V_q0.read().range(31, 10);
}

void calcHaarPattern_x_y::thread_ret_V_4_fu_418_p2() {
    ret_V_4_fu_418_p2 = (!ret_V_3_fu_390_p4.read().is_01() || !ap_const_lv22_1.is_01())? sc_lv<22>(): (sc_biguint<22>(ret_V_3_fu_390_p4.read()) + sc_biguint<22>(ap_const_lv22_1));
}

void calcHaarPattern_x_y::thread_ret_V_5_fu_480_p4() {
    ret_V_5_fu_480_p4 = box_0_V_q0.read().range(31, 10);
}

void calcHaarPattern_x_y::thread_ret_V_6_fu_508_p2() {
    ret_V_6_fu_508_p2 = (!ret_V_5_fu_480_p4.read().is_01() || !ap_const_lv22_1.is_01())? sc_lv<22>(): (sc_biguint<22>(ret_V_5_fu_480_p4.read()) + sc_biguint<22>(ap_const_lv22_1));
}

void calcHaarPattern_x_y::thread_ret_V_7_fu_563_p4() {
    ret_V_7_fu_563_p4 = box_1_V_q0.read().range(31, 10);
}

void calcHaarPattern_x_y::thread_ret_V_8_fu_591_p2() {
    ret_V_8_fu_591_p2 = (!ret_V_7_fu_563_p4.read().is_01() || !ap_const_lv22_1.is_01())? sc_lv<22>(): (sc_biguint<22>(ret_V_7_fu_563_p4.read()) + sc_biguint<22>(ap_const_lv22_1));
}

void calcHaarPattern_x_y::thread_ret_V_fu_307_p4() {
    ret_V_fu_307_p4 = box_2_V_q0.read().range(31, 10);
}

void calcHaarPattern_x_y::thread_sumBuf_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        sumBuf_address0 =  (sc_lv<15>) (tmp_82_cast_fu_901_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        sumBuf_address0 =  (sc_lv<15>) (tmp_77_cast_fu_879_p1.read());
    } else {
        sumBuf_address0 = "XXXXXXXXXXXXXXX";
    }
}

void calcHaarPattern_x_y::thread_sumBuf_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        sumBuf_address1 =  (sc_lv<15>) (tmp_83_cast_fu_905_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        sumBuf_address1 =  (sc_lv<15>) (tmp_78_cast_fu_888_p1.read());
    } else {
        sumBuf_address1 = "XXXXXXXXXXXXXXX";
    }
}

void calcHaarPattern_x_y::thread_sumBuf_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        sumBuf_ce0 = ap_const_logic_1;
    } else {
        sumBuf_ce0 = ap_const_logic_0;
    }
}

void calcHaarPattern_x_y::thread_sumBuf_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        sumBuf_ce1 = ap_const_logic_1;
    } else {
        sumBuf_ce1 = ap_const_logic_0;
    }
}

void calcHaarPattern_x_y::thread_tmp_106_fu_325_p1() {
    tmp_106_fu_325_p1 = box_2_V_q0.read().range(10-1, 0);
}

void calcHaarPattern_x_y::thread_tmp_107_fu_341_p1() {
    tmp_107_fu_341_p1 = esl_zext<16,11>(cOffset.read());
}

void calcHaarPattern_x_y::thread_tmp_108_fu_344_p4() {
    tmp_108_fu_344_p4 = box_2_V_q0.read().range(25, 10);
}

void calcHaarPattern_x_y::thread_tmp_109_fu_354_p1() {
    tmp_109_fu_354_p1 = ret_V_2_fu_335_p2.read().range(16-1, 0);
}

void calcHaarPattern_x_y::thread_tmp_10_fu_502_p2() {
    tmp_10_fu_502_p2 = (!tmp_135_fu_498_p1.read().is_01() || !ap_const_lv10_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_135_fu_498_p1.read() == ap_const_lv10_0);
}

void calcHaarPattern_x_y::thread_tmp_110_fu_358_p3() {
    tmp_110_fu_358_p3 = (!tmp_2_fu_329_p2.read()[0].is_01())? sc_lv<16>(): ((tmp_2_fu_329_p2.read()[0].to_bool())? tmp_108_fu_344_p4.read(): tmp_109_fu_354_p1.read());
}

void calcHaarPattern_x_y::thread_tmp_111_fu_366_p4() {
    tmp_111_fu_366_p4 = box_2_V_q0.read().range(25, 10);
}

void calcHaarPattern_x_y::thread_tmp_112_fu_376_p3() {
    tmp_112_fu_376_p3 = (!p_Result_s_fu_317_p3.read()[0].is_01())? sc_lv<16>(): ((p_Result_s_fu_317_p3.read()[0].to_bool())? tmp_110_fu_358_p3.read(): tmp_111_fu_366_p4.read());
}

void calcHaarPattern_x_y::thread_tmp_113_fu_384_p2() {
    tmp_113_fu_384_p2 = (!tmp_107_fu_341_p1.read().is_01() || !tmp_112_fu_376_p3.read().is_01())? sc_lv<16>(): (sc_biguint<16>(tmp_107_fu_341_p1.read()) + sc_biguint<16>(tmp_112_fu_376_p3.read()));
}

void calcHaarPattern_x_y::thread_tmp_115_fu_408_p1() {
    tmp_115_fu_408_p1 = box_3_V_q0.read().range(10-1, 0);
}

void calcHaarPattern_x_y::thread_tmp_116_fu_472_p1() {
    tmp_116_fu_472_p1 = tmp_9_fu_467_p2.read().range(5-1, 0);
}

void calcHaarPattern_x_y::thread_tmp_117_fu_667_p2() {
    tmp_117_fu_667_p2 = (!Lo_assign_fu_663_p1.read().is_01() || !Hi_assign_cast_fu_653_p1.read().is_01())? sc_lv<1>(): (sc_biguint<32>(Lo_assign_fu_663_p1.read()) > sc_biguint<32>(Hi_assign_cast_fu_653_p1.read()));
}

void calcHaarPattern_x_y::thread_tmp_118_fu_673_p3() {
    tmp_118_fu_673_p3 = esl_concat<5,3>(tmp_116_reg_1027.read(), ap_const_lv3_0);
}

void calcHaarPattern_x_y::thread_tmp_119_fu_476_p1() {
    tmp_119_fu_476_p1 = Hi_assign_fu_461_p2.read().range(8-1, 0);
}

void calcHaarPattern_x_y::thread_tmp_11_fu_875_p2() {
    tmp_11_fu_875_p2 = (!tmp_8_reg_1080.read().is_01() || !tmp_113_reg_1011.read().is_01())? sc_lv<16>(): (sc_bigint<16>(tmp_8_reg_1080.read()) + sc_biguint<16>(tmp_113_reg_1011.read()));
}

void calcHaarPattern_x_y::thread_tmp_120_fu_680_p4() {
    tmp_120_fu_680_p4 = sumBufIndex_V.read().range(0, 175);
}

void calcHaarPattern_x_y::thread_tmp_121_fu_689_p2() {
    tmp_121_fu_689_p2 = (!tmp_118_fu_673_p3.read().is_01() || !tmp_119_reg_1032.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_118_fu_673_p3.read()) - sc_biguint<8>(tmp_119_reg_1032.read()));
}

void calcHaarPattern_x_y::thread_tmp_122_fu_694_p2() {
    tmp_122_fu_694_p2 = (!ap_const_lv8_AF.is_01() || !tmp_118_fu_673_p3.read().is_01())? sc_lv<8>(): (sc_bigint<8>(ap_const_lv8_AF) - sc_biguint<8>(tmp_118_fu_673_p3.read()));
}

void calcHaarPattern_x_y::thread_tmp_123_fu_700_p2() {
    tmp_123_fu_700_p2 = (!tmp_119_reg_1032.read().is_01() || !tmp_118_fu_673_p3.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_119_reg_1032.read()) - sc_biguint<8>(tmp_118_fu_673_p3.read()));
}

void calcHaarPattern_x_y::thread_tmp_124_fu_705_p3() {
    tmp_124_fu_705_p3 = (!tmp_117_fu_667_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_117_fu_667_p2.read()[0].to_bool())? tmp_121_fu_689_p2.read(): tmp_123_fu_700_p2.read());
}

void calcHaarPattern_x_y::thread_tmp_125_fu_713_p3() {
    tmp_125_fu_713_p3 = (!tmp_117_fu_667_p2.read()[0].is_01())? sc_lv<176>(): ((tmp_117_fu_667_p2.read()[0].to_bool())? tmp_120_fu_680_p4.read(): sumBufIndex_V.read());
}

void calcHaarPattern_x_y::thread_tmp_126_fu_720_p3() {
    tmp_126_fu_720_p3 = (!tmp_117_fu_667_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_117_fu_667_p2.read()[0].to_bool())? tmp_122_fu_694_p2.read(): tmp_118_fu_673_p3.read());
}

void calcHaarPattern_x_y::thread_tmp_127_fu_728_p2() {
    tmp_127_fu_728_p2 = (!ap_const_lv8_AF.is_01() || !tmp_124_fu_705_p3.read().is_01())? sc_lv<8>(): (sc_bigint<8>(ap_const_lv8_AF) - sc_biguint<8>(tmp_124_fu_705_p3.read()));
}

void calcHaarPattern_x_y::thread_tmp_128_fu_734_p1() {
    tmp_128_fu_734_p1 = esl_zext<176,8>(tmp_126_fu_720_p3.read());
}

void calcHaarPattern_x_y::thread_tmp_129_fu_738_p1() {
    tmp_129_fu_738_p1 = esl_zext<176,8>(tmp_127_fu_728_p2.read());
}

void calcHaarPattern_x_y::thread_tmp_12_fu_884_p2() {
    tmp_12_fu_884_p2 = (!tmp_8_reg_1080.read().is_01() || !tmp_142_reg_1038.read().is_01())? sc_lv<16>(): (sc_bigint<16>(tmp_8_reg_1080.read()) + sc_biguint<16>(tmp_142_reg_1038.read()));
}

void calcHaarPattern_x_y::thread_tmp_130_fu_742_p2() {
    tmp_130_fu_742_p2 = (!tmp_128_fu_734_p1.read().is_01())? sc_lv<176>(): tmp_125_fu_713_p3.read() >> (unsigned short)tmp_128_fu_734_p1.read().to_uint();
}

void calcHaarPattern_x_y::thread_tmp_131_fu_748_p2() {
    tmp_131_fu_748_p2 = (!tmp_129_fu_738_p1.read().is_01())? sc_lv<176>(): ap_const_lv176_lc_1 >> (unsigned short)tmp_129_fu_738_p1.read().to_uint();
}

void calcHaarPattern_x_y::thread_tmp_133_fu_760_p1() {
    tmp_133_fu_760_p1 = p_Result_5_fu_754_p2.read().range(16-1, 0);
}

void calcHaarPattern_x_y::thread_tmp_135_fu_498_p1() {
    tmp_135_fu_498_p1 = box_0_V_q0.read().range(10-1, 0);
}

void calcHaarPattern_x_y::thread_tmp_136_fu_514_p1() {
    tmp_136_fu_514_p1 = esl_zext<16,11>(cOffset.read());
}

void calcHaarPattern_x_y::thread_tmp_137_fu_517_p4() {
    tmp_137_fu_517_p4 = box_0_V_q0.read().range(25, 10);
}

void calcHaarPattern_x_y::thread_tmp_138_fu_527_p1() {
    tmp_138_fu_527_p1 = ret_V_6_fu_508_p2.read().range(16-1, 0);
}

void calcHaarPattern_x_y::thread_tmp_139_fu_531_p3() {
    tmp_139_fu_531_p3 = (!tmp_10_fu_502_p2.read()[0].is_01())? sc_lv<16>(): ((tmp_10_fu_502_p2.read()[0].to_bool())? tmp_137_fu_517_p4.read(): tmp_138_fu_527_p1.read());
}

void calcHaarPattern_x_y::thread_tmp_13_fu_585_p2() {
    tmp_13_fu_585_p2 = (!tmp_144_fu_581_p1.read().is_01() || !ap_const_lv10_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_144_fu_581_p1.read() == ap_const_lv10_0);
}

void calcHaarPattern_x_y::thread_tmp_140_fu_539_p4() {
    tmp_140_fu_539_p4 = box_0_V_q0.read().range(25, 10);
}

void calcHaarPattern_x_y::thread_tmp_141_fu_549_p3() {
    tmp_141_fu_549_p3 = (!p_Result_6_fu_490_p3.read()[0].is_01())? sc_lv<16>(): ((p_Result_6_fu_490_p3.read()[0].to_bool())? tmp_139_fu_531_p3.read(): tmp_140_fu_539_p4.read());
}

void calcHaarPattern_x_y::thread_tmp_142_fu_557_p2() {
    tmp_142_fu_557_p2 = (!tmp_136_fu_514_p1.read().is_01() || !tmp_141_fu_549_p3.read().is_01())? sc_lv<16>(): (sc_biguint<16>(tmp_136_fu_514_p1.read()) + sc_biguint<16>(tmp_141_fu_549_p3.read()));
}

void calcHaarPattern_x_y::thread_tmp_144_fu_581_p1() {
    tmp_144_fu_581_p1 = box_1_V_q0.read().range(10-1, 0);
}

void calcHaarPattern_x_y::thread_tmp_145_fu_645_p1() {
    tmp_145_fu_645_p1 = tmp_16_fu_640_p2.read().range(5-1, 0);
}

void calcHaarPattern_x_y::thread_tmp_146_fu_778_p2() {
    tmp_146_fu_778_p2 = (!Lo_assign_3_fu_774_p1.read().is_01() || !Hi_assign_3_cast_fu_764_p1.read().is_01())? sc_lv<1>(): (sc_biguint<32>(Lo_assign_3_fu_774_p1.read()) > sc_biguint<32>(Hi_assign_3_cast_fu_764_p1.read()));
}

void calcHaarPattern_x_y::thread_tmp_147_fu_784_p3() {
    tmp_147_fu_784_p3 = esl_concat<5,3>(tmp_145_reg_1054.read(), ap_const_lv3_0);
}

void calcHaarPattern_x_y::thread_tmp_148_fu_649_p1() {
    tmp_148_fu_649_p1 = Hi_assign_3_fu_634_p2.read().range(8-1, 0);
}

void calcHaarPattern_x_y::thread_tmp_149_fu_791_p4() {
    tmp_149_fu_791_p4 = sumBufIndex_V.read().range(0, 175);
}

void calcHaarPattern_x_y::thread_tmp_14_fu_617_p2() {
    tmp_14_fu_617_p2 = (!tmp_53_cast_fu_613_p1.read().is_01() || !tmp_22_cast_reg_972.read().is_01())? sc_lv<23>(): (sc_bigint<23>(tmp_53_cast_fu_613_p1.read()) + sc_bigint<23>(tmp_22_cast_reg_972.read()));
}

void calcHaarPattern_x_y::thread_tmp_150_fu_800_p2() {
    tmp_150_fu_800_p2 = (!tmp_147_fu_784_p3.read().is_01() || !tmp_148_reg_1059.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_147_fu_784_p3.read()) - sc_biguint<8>(tmp_148_reg_1059.read()));
}

void calcHaarPattern_x_y::thread_tmp_151_fu_805_p2() {
    tmp_151_fu_805_p2 = (!ap_const_lv8_AF.is_01() || !tmp_147_fu_784_p3.read().is_01())? sc_lv<8>(): (sc_bigint<8>(ap_const_lv8_AF) - sc_biguint<8>(tmp_147_fu_784_p3.read()));
}

void calcHaarPattern_x_y::thread_tmp_152_fu_811_p2() {
    tmp_152_fu_811_p2 = (!tmp_148_reg_1059.read().is_01() || !tmp_147_fu_784_p3.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_148_reg_1059.read()) - sc_biguint<8>(tmp_147_fu_784_p3.read()));
}

void calcHaarPattern_x_y::thread_tmp_153_fu_816_p3() {
    tmp_153_fu_816_p3 = (!tmp_146_fu_778_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_146_fu_778_p2.read()[0].to_bool())? tmp_150_fu_800_p2.read(): tmp_152_fu_811_p2.read());
}

void calcHaarPattern_x_y::thread_tmp_154_fu_824_p3() {
    tmp_154_fu_824_p3 = (!tmp_146_fu_778_p2.read()[0].is_01())? sc_lv<176>(): ((tmp_146_fu_778_p2.read()[0].to_bool())? tmp_149_fu_791_p4.read(): sumBufIndex_V.read());
}

void calcHaarPattern_x_y::thread_tmp_155_fu_831_p3() {
    tmp_155_fu_831_p3 = (!tmp_146_fu_778_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_146_fu_778_p2.read()[0].to_bool())? tmp_151_fu_805_p2.read(): tmp_147_fu_784_p3.read());
}

void calcHaarPattern_x_y::thread_tmp_156_fu_839_p2() {
    tmp_156_fu_839_p2 = (!ap_const_lv8_AF.is_01() || !tmp_153_fu_816_p3.read().is_01())? sc_lv<8>(): (sc_bigint<8>(ap_const_lv8_AF) - sc_biguint<8>(tmp_153_fu_816_p3.read()));
}

void calcHaarPattern_x_y::thread_tmp_157_fu_845_p1() {
    tmp_157_fu_845_p1 = esl_zext<176,8>(tmp_155_fu_831_p3.read());
}

void calcHaarPattern_x_y::thread_tmp_158_fu_849_p1() {
    tmp_158_fu_849_p1 = esl_zext<176,8>(tmp_156_fu_839_p2.read());
}

void calcHaarPattern_x_y::thread_tmp_159_fu_853_p2() {
    tmp_159_fu_853_p2 = (!tmp_157_fu_845_p1.read().is_01())? sc_lv<176>(): tmp_154_fu_824_p3.read() >> (unsigned short)tmp_157_fu_845_p1.read().to_uint();
}

void calcHaarPattern_x_y::thread_tmp_15_cast_fu_630_p1() {
    tmp_15_cast_fu_630_p1 = esl_sext<27,26>(tmp_15_fu_622_p3.read());
}

void calcHaarPattern_x_y::thread_tmp_15_fu_622_p3() {
    tmp_15_fu_622_p3 = esl_concat<23,3>(tmp_14_fu_617_p2.read(), ap_const_lv3_0);
}

void calcHaarPattern_x_y::thread_tmp_160_fu_859_p2() {
    tmp_160_fu_859_p2 = (!tmp_158_fu_849_p1.read().is_01())? sc_lv<176>(): ap_const_lv176_lc_1 >> (unsigned short)tmp_158_fu_849_p1.read().to_uint();
}

void calcHaarPattern_x_y::thread_tmp_162_fu_871_p1() {
    tmp_162_fu_871_p1 = p_Result_8_fu_865_p2.read().range(16-1, 0);
}

void calcHaarPattern_x_y::thread_tmp_16_fu_640_p2() {
    tmp_16_fu_640_p2 = (!tmp_cast1_reg_966.read().is_01() || !tmp_53_cast_fu_613_p1.read().is_01())? sc_lv<23>(): (sc_bigint<23>(tmp_cast1_reg_966.read()) + sc_bigint<23>(tmp_53_cast_fu_613_p1.read()));
}

void calcHaarPattern_x_y::thread_tmp_17_fu_767_p3() {
    tmp_17_fu_767_p3 = esl_concat<23,3>(tmp_16_reg_1049.read(), ap_const_lv3_0);
}

void calcHaarPattern_x_y::thread_tmp_18_fu_909_p2() {
    tmp_18_fu_909_p2 = (!sumBuf_q0.read().is_01() || !sumBuf_q1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(sumBuf_q0.read()) - sc_biguint<32>(sumBuf_q1.read()));
}

void calcHaarPattern_x_y::thread_tmp_19_fu_915_p2() {
    tmp_19_fu_915_p2 = (!tmp_18_reg_1116.read().is_01() || !sumBuf_q0.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_18_reg_1116.read()) - sc_biguint<32>(sumBuf_q0.read()));
}

void calcHaarPattern_x_y::thread_tmp_1_fu_267_p2() {
    tmp_1_fu_267_p2 = (!tmp_cast_fu_263_p1.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_bigint<7>(tmp_cast_fu_263_p1.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void calcHaarPattern_x_y::thread_tmp_20_fu_940_p1() {
    tmp_20_fu_940_p1 =  (sc_lv<11>) (ap_const_lv16_321);
}

void calcHaarPattern_x_y::thread_tmp_21_fu_893_p2() {
    tmp_21_fu_893_p2 = (!tmp_20_fu_940_p2.read().is_01() || !tmp_113_reg_1011.read().is_01())? sc_lv<16>(): (sc_bigint<16>(tmp_20_fu_940_p2.read()) + sc_biguint<16>(tmp_113_reg_1011.read()));
}

void calcHaarPattern_x_y::thread_tmp_22_cast_fu_273_p1() {
    tmp_22_cast_fu_273_p1 = esl_sext<23,7>(tmp_1_fu_267_p2.read());
}

void calcHaarPattern_x_y::thread_tmp_22_fu_897_p2() {
    tmp_22_fu_897_p2 = (!tmp_20_fu_940_p2.read().is_01() || !tmp_142_reg_1038.read().is_01())? sc_lv<16>(): (sc_bigint<16>(tmp_20_fu_940_p2.read()) + sc_biguint<16>(tmp_142_reg_1038.read()));
}

void calcHaarPattern_x_y::thread_tmp_27_cast_fu_440_p1() {
    tmp_27_cast_fu_440_p1 = esl_sext<23,22>(p_2_fu_432_p3.read());
}

void calcHaarPattern_x_y::thread_tmp_2_fu_329_p2() {
    tmp_2_fu_329_p2 = (!tmp_106_fu_325_p1.read().is_01() || !ap_const_lv10_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_106_fu_325_p1.read() == ap_const_lv10_0);
}

void calcHaarPattern_x_y::thread_tmp_3_fu_293_p2() {
    tmp_3_fu_293_p2 = (!tmp_s_reg_961.read().is_01() || !tmp_cast_41_fu_289_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(tmp_s_reg_961.read()) + sc_biguint<5>(tmp_cast_41_fu_289_p1.read()));
}

void calcHaarPattern_x_y::thread_tmp_4_fu_449_p3() {
    tmp_4_fu_449_p3 = esl_concat<23,3>(tmp_6_fu_444_p2.read(), ap_const_lv3_0);
}

void calcHaarPattern_x_y::thread_tmp_53_cast_fu_613_p1() {
    tmp_53_cast_fu_613_p1 = esl_sext<23,22>(p_4_fu_605_p3.read());
}

void calcHaarPattern_x_y::thread_tmp_5_fu_412_p2() {
    tmp_5_fu_412_p2 = (!tmp_115_fu_408_p1.read().is_01() || !ap_const_lv10_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_115_fu_408_p1.read() == ap_const_lv10_0);
}

void calcHaarPattern_x_y::thread_tmp_6_fu_444_p2() {
    tmp_6_fu_444_p2 = (!tmp_27_cast_fu_440_p1.read().is_01() || !tmp_22_cast_reg_972.read().is_01())? sc_lv<23>(): (sc_bigint<23>(tmp_27_cast_fu_440_p1.read()) + sc_bigint<23>(tmp_22_cast_reg_972.read()));
}

void calcHaarPattern_x_y::thread_tmp_73_cast_fu_298_p1() {
    tmp_73_cast_fu_298_p1 = esl_sext<64,5>(tmp_3_fu_293_p2.read());
}

void calcHaarPattern_x_y::thread_tmp_77_cast_fu_879_p1() {
    tmp_77_cast_fu_879_p1 = esl_zext<64,16>(tmp_11_fu_875_p2.read());
}

void calcHaarPattern_x_y::thread_tmp_78_cast_fu_888_p1() {
    tmp_78_cast_fu_888_p1 = esl_zext<64,16>(tmp_12_fu_884_p2.read());
}

void calcHaarPattern_x_y::thread_tmp_7_fu_656_p3() {
    tmp_7_fu_656_p3 = esl_concat<23,3>(tmp_9_reg_1022.read(), ap_const_lv3_0);
}

void calcHaarPattern_x_y::thread_tmp_82_cast_fu_901_p1() {
    tmp_82_cast_fu_901_p1 = esl_zext<64,16>(tmp_21_reg_1096.read());
}

void calcHaarPattern_x_y::thread_tmp_83_cast_fu_905_p1() {
    tmp_83_cast_fu_905_p1 = esl_zext<64,16>(tmp_22_reg_1101.read());
}

void calcHaarPattern_x_y::thread_tmp_8_cast_fu_457_p1() {
    tmp_8_cast_fu_457_p1 = esl_sext<27,26>(tmp_4_fu_449_p3.read());
}

void calcHaarPattern_x_y::thread_tmp_8_fu_935_p1() {
    tmp_8_fu_935_p1 =  (sc_lv<11>) (ap_const_lv16_321);
}

void calcHaarPattern_x_y::thread_tmp_9_fu_467_p2() {
    tmp_9_fu_467_p2 = (!tmp_cast1_reg_966.read().is_01() || !tmp_27_cast_fu_440_p1.read().is_01())? sc_lv<23>(): (sc_bigint<23>(tmp_cast1_reg_966.read()) + sc_bigint<23>(tmp_27_cast_fu_440_p1.read()));
}

void calcHaarPattern_x_y::thread_tmp_V_fu_920_p2() {
    tmp_V_fu_920_p2 = (!tmp_19_fu_915_p2.read().is_01() || !sumBuf_q1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_19_fu_915_p2.read()) + sc_biguint<32>(sumBuf_q1.read()));
}

void calcHaarPattern_x_y::thread_tmp_cast1_fu_259_p0() {
    tmp_cast1_fu_259_p0 = rOffset.read();
}

void calcHaarPattern_x_y::thread_tmp_cast1_fu_259_p1() {
    tmp_cast1_fu_259_p1 = esl_sext<23,6>(tmp_cast1_fu_259_p0.read());
}

void calcHaarPattern_x_y::thread_tmp_cast_41_fu_289_p1() {
    tmp_cast_41_fu_289_p1 = esl_zext<5,2>(kn_reg_226.read());
}

void calcHaarPattern_x_y::thread_tmp_cast_fu_263_p0() {
    tmp_cast_fu_263_p0 = rOffset.read();
}

void calcHaarPattern_x_y::thread_tmp_cast_fu_263_p1() {
    tmp_cast_fu_263_p1 = esl_sext<7,6>(tmp_cast_fu_263_p0.read());
}

void calcHaarPattern_x_y::thread_tmp_fu_241_p3() {
    tmp_fu_241_p3 = esl_concat<2,2>(box_V_offset.read(), ap_const_lv2_0);
}

void calcHaarPattern_x_y::thread_tmp_s_fu_253_p2() {
    tmp_s_fu_253_p2 = (!p_shl_cast_fu_249_p1.read().is_01() || !box_V_offset_cast_ca_fu_237_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(p_shl_cast_fu_249_p1.read()) - sc_biguint<5>(box_V_offset_cast_ca_fu_237_p1.read()));
}

void calcHaarPattern_x_y::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond_fu_277_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<10>) ("XXXXXXXXXX");
            break;
    }
}

}

